M48
; DRILL file {KiCad 7.0.8} date Fri 10 Nov 2023 01:40:48 AM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-10T01:40:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
%
G90
G05
T1
X73.45Y-69.76
X73.465Y-81.23
X73.51Y-94.51
X74.72Y-124.97
X99.28Y-122.01
T0
M30
