M48
; DRILL file {KiCad 7.0.10} date Sun 04 Feb 2024 11:07:43 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-04T23:07:43+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
%
G90
G05
T1
X73.45Y-69.76
X73.465Y-81.23
X73.51Y-94.51
X74.72Y-124.97
X99.28Y-122.01
M30
